### ISSUE TITLE
Program not installing

### ISSUE THREAD

**Issue by AdamM1985** [csiqueirasilva/PoEController#11]
Hi I've used your program before and loved it. I decided to play some POE again and had to re download and install Path of Exile on steam, and PoEController. I have tried multiple times now and when I download the files I save it onto my desktop but it's just a bunch of folders that lead to wordpad. I don't remember having this issue before. I apologize for troubling you, any help would be greatly appreciated. Thank you and have a great night.

**Comment by csiqueirasilva** [comment]
Hi! Are you sure you didnt downloaded the source code instead of the installer?

**Comment by AdamM1985** [comment]
Thanks for the reply.

I don't know, I hope it's that simple. When I go to the POE controller page I just click on the green tab that says clone or download and then I choose zip file.

**Comment by AdamM1985** [comment]
You were right I kept downloading the source code....

I finally got it working now. Thanks for your help and this awesome program!
