### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by AdamM1985** [csiqueirasilva/PoEController#13]
Hello, every time I start up PoE Controller my entire screen goes white. When I close the program my pc goes back to normal.

Any idea what this is happening?

**Comment by csiqueirasilva** [comment]
The screen stays the same while the program is running? It is normal to have a slowdown while it is loading. The program has an overlay that is on fullscreen mode, and it sometimes appears here as if my whole screen turned into white.

**Comment by AdamM1985** [comment]
Thanks for the reply. When I double click PoE controller my entire screen goes white. I can't even start the game or do anything else. My only option is to press windows key and they right click the poe controller program on my task bar and close it.

I just bought a new pc and reinstalled everything so I have used this program before but now I just get a blank white screen, no idea why or how to fix it. I was hoping maybe you can across this before. I apologize for the trouble.

**Comment by AdamM1985** [comment]
I just changed my screen backround for the first time on this new pc and the program works now.

Dumbest solution ever....

Thanks again for your help and sorry for all the trouble. Problem solved!

**Comment by AdamM1985** [comment]
Any idea how to fix the left analog movement? Normally it's centered around the red dot in the middle of the screen but when I start the game I can't move in the direction I want to because rather than being centered in the middle it's in the top left. Not sue if what I said just made sense.

**Comment by csiqueirasilva** [comment]
The program has a lot of bugs right now, but it should still be usable. I'm closing this issue since the original question has been answered.
