### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by AmanitaVerna** [csiqueirasilva/PoEController#14]
(Using a wireless xbox 360 controller with microsoft's adapter)

It launches (Steam) PoE and displays the overlay properly, but moving the sticks does nothing, and pressing buttons on the controller does nothing. Even after logging in and choosing a character and getting into the game proper, no input from the controller reaches the game.

Also I notice there's no mapping for T.

I downloaded the source to poke it, but I don't have any clue how to compile it, and there don't appear to be any compiling instructions.

**Comment by csiqueirasilva** [comment]
I'm working on a compile guide! Just don't have much time on me right now. Maybe next week it will be available.

**Comment by csiqueirasilva** [comment]
added a xinput mode to the latest tag (pre-release); should fix this.
