### ISSUE TITLE
Menu UI Doesn't Change in Game

### ISSUE THREAD

**Issue by moxjet200** [csiqueirasilva/PoEController#15]
When pressing start in game the UI does not change correctly. If I open a browser or file explorer window and maximize it, then press start, the UI does change correctly like it needs to in-game.

**Comment by csiqueirasilva** [comment]
Hello! As answered on reddit, this issue is due to the program's interface not being in sync with the current UI updates PoE had. The code needs a maintenance to fix it. It shouldnt be hard, but I cant commit to do it now. However, i'm trying to write a guide on how to compile it (under Node).

**Comment by csiqueirasilva** [comment]
this feature was dropped in favor of better maintainability
