### ISSUE TITLE
can't run the program itself on 1920*1080

### ISSUE THREAD

**Issue by Zittra** [csiqueirasilva/PoEController#16]
Hi! I can't start the porgram itself on 1920*1080. Do you have any suggestion to make it work? thx

**Comment by csiqueirasilva** [comment]
hmm It should work. Can you post some screenshots or more info of whats happening?

**Comment by Zittra** [comment]
Sure! thx!

<img width="960" alt="screenshot 2017-06-04 19 54 34" src="https://cloud.githubusercontent.com/assets/29178501/26764070/ec56ffc6-495f-11e7-9503-1a98e316f23d.png">

**Comment by csiqueirasilva** [comment]
What about the game configuration? Is it on windowed full screen with one of the supported resolution?

**Comment by Zittra** [comment]
yep

borderless_windowed_fullscreen=true
***
resolution_height=1080
resolution_width=192

**Comment by Zittra** [comment]
its 1920

**Comment by csiqueirasilva** [comment]
Well the only other option I see is to try the 1080i 1920x1080. I dont know why it is not correctly identifying your resolution, as it should!

**Comment by Zittra** [comment]
Great. thx man looking forward to try your program.

**Comment by csiqueirasilva** [comment]
application no longer tied to specific resolutions, as pixel reading was dropped entirely
