### ISSUE TITLE
Coniguration file and Xbox Driver

### ISSUE THREAD

**Issue by SonofaPun** [csiqueirasilva/PoEController#17]
Hi, I get 2 errors when trying to run the program. One about the xbox controller driver, and one about not being able to locate the poe config file.
![screenshot_1](https://user-images.githubusercontent.com/20741073/30221620-9766b004-9489-11e7-8f64-750a35cf77e1.png)

**Comment by csiqueirasilva** [comment]
Maybe it is a permission issue. Can you try running it as admin?

**Comment by SonofaPun** [comment]
Hmm, nope. Same problem

**Comment by sigmaprojects** [comment]
Same issue...

**Comment by csiqueirasilva** [comment]
@sigmaprojects The code is looking for these locations:
process.env['USERPROFILE'] and concatenates one of the two (it tries to find them in this order):

- \Documents\My Games\Path of Exile\production_Config.ini
- \My Documents\My Games\Path of Exile\production_Config.ini

You could check in the command prompt the value of %USERPROFILE% to find out the full path of the configuraton file that PoEController is trying to find (shortcut keys to check this: windows + r (run); type "cmd" and press enter; type "echo %USERPROFILE%" and press enter in the command prompt window. The return value below the line where you did input the command should be the value of process.env['USERPROFILE']).

**Comment by sigmaprojects** [comment]
There's something funky about my setup.  I was able to fix the "Could not find PoE config file" error by creating a mklink from c:\users\don\Documents \\unc\to\docs though it had unintended consequences: https://i.imgur.com/auqRncN.png

Now the only error is about the controller.  Shibari see's it just fine https://i.imgur.com/GmF7qdf.png

Any ideas?

**Comment by csiqueirasilva** [comment]
I understand you want to use Shibari as your device interface, but it is stated in their page:

"Target audience: You're running Windows 8.1 or 10, wanna use your DualShock 3 controller in pretty much any game and can't run/don't want to deal with ScpToolkit. You might give this a shot then 😊".

From that, I think their driver method for dualshock 3 must be quite different from how ScpToolkit does it (even it is just a version). Can't you give ScpTookit a shot?

(About your UNC problem: check file extensions. The link could end with .lnk)

**Comment by sigmaprojects** [comment]
Removed Shibari & it's misc driver.  ScpTookit installed & recognized the controller but the "error while connecting controller" error is still there

**Comment by csiqueirasilva** [comment]
@sigmaprojects i could reproduce the error here. something is wrong with the xbox-controller-node library. i'm checking it out. Lets hope I can finish this asap, so youll be able to enjoy the new league tomorrow with PoEController.

**Comment by csiqueirasilva** [comment]
@sigmaprojects i was able to rebuild the code and solved your issue. however, i wont have time to reship a new package before the delve league start this weekend :-(

**Comment by csiqueirasilva** [comment]
@sigmaprojects Hi. I finished a build that attempts to fix your problem. Please uninstall any previous version of PoEController and [try this if you want](https://github.com/csiqueirasilva/PoEController/releases/tag/v1.1).

**Comment by sigmaprojects** [comment]
Thank you so much - controller was detected and working
