### ISSUE TITLE
Should not run steam...

### ISSUE THREAD

**Issue by adderek** [csiqueirasilva/PoEController#20]
I have a non-steam version. Nevertheless the game starts steam (so it runs steam update and shows game installation dialogue).
It should not even attempt to run steam IF the game is running.
Since it can loose the controller somehow (I have no idea what exactly happens) I need to stop and start controller again - leading to another attempt of steam startup while game is still running in the background.

**Comment by csiqueirasilva** [comment]
Hi! When developing this (3 years ago!), I decided to tie the tool to the steam version of the game (at the time, it appeared that the support for the standalone client would drop. I couldnt be more wrong).

**Comment by csiqueirasilva** [comment]
no longer tied to steamversion, as gamePath config was added to the configuration file
