### ISSUE TITLE
PoE Controller (Xbox one controller): Error

### ISSUE THREAD

**Issue by Lumsword** [csiqueirasilva/PoEController#29]
When I tried to open PoEController program, the error popped saying "Could not find Path of Exile's configuration file" and it closed automatically. So, how do I fix this? Yes, I really wanna play PoE using a xbox one controller.

Thank you for your time and aid on this little error.

**Comment by csiqueirasilva** [comment]
Sorry this took so long. I submitted a pre-release that should fix this issue.
