### ISSUE TITLE
Game must be on C: drive

### ISSUE THREAD

**Issue by csiqueirasilva** [csiqueirasilva/PoEController#9]
> Hey bud,
> I'm getting the same error. I found that it's related to the fact that I have my (C:) drive's Documents > folder redirected to another drive. I was able to manually place the Path of Exile folder on my (C:) drive to get it working.
> Hope that helps some troubleshooting! Awesome tool, by the way. Thanks for all your hard work.
> -- <i>reddit user Zimplicio</i>

**Comment by BrosephJ** [comment]
This isn't fixed still. I don't use the default Documents directory so I had to use a program to create a symbolic link so the program could find my PoE folder. >_>

**Comment by CristenPerret** [comment]
Also running into an issue with the software. My OS is only on my C Drive. At least having a way to direct the pathing to a custom location would be nice. I dont want to get into the headache of making a symbolic link, is there no editable file to adjust the generic directory?

**Comment by csiqueirasilva** [comment]
i think you can edit the script files to set up a path. symlink seems
easier tho.

**Comment by csiqueirasilva** [comment]
added a configuration parameter to fix this issue
